/* Exemples de réponses aux prompts (dossier exemples/) : un même cas d'usage appliqué à chaque carte recette.
   Fichier généré avec le dossier exemples ; la page exemple.html affiche la réponse d'une carte. */

window.EXEMPLES = {
  sujet: "Comment améliorer les interactions dans une formation d’adultes ?",
  publicCible: "Formateurs d’adultes",
  reponses: {
  "5-pourquoi": "exemples/reponses/01-5-pourquoi.md",
  "accelerateur-de-projet": "exemples/reponses/02-accelerateur-de-projet.md",
  "analyse-swot": "exemples/reponses/03-analyse-swot.md",
  "arpentage": "exemples/reponses/04-arpentage.md",
  "baton-dhelium": "exemples/reponses/05-baton-dhelium.md",
  "baton-de-parole": "exemples/reponses/06-baton-de-parole.md",
  "bodystorming": "exemples/reponses/07-bodystorming.md",
  "carte-mentale": "exemples/reponses/08-carte-mentale.md",
  "cercle-de-parole": "exemples/reponses/09-cercle-de-parole.md",
  "cercle-samoan": "exemples/reponses/10-cercle-samoan.md",
  "chifoumi-collectif-pierre-feuille-ciseaux": "exemples/reponses/11-chifoumi-collectif-pierre-feuille-ciseaux.md",
  "debat-mouvant": "exemples/reponses/12-debat-mouvant.md",
  "decision-par-consentement": "exemples/reponses/13-decision-par-consentement.md",
  "demande-de-silence": "exemples/reponses/14-demande-de-silence.md",
  "diagramme-avec-les-pieds": "exemples/reponses/15-diagramme-avec-les-pieds.md",
  "discussion-ascenceur": "exemples/reponses/16-discussion-ascenceur.md",
  "discussion-kanak": "exemples/reponses/17-discussion-kanak.md",
  "documentation-croisee": "exemples/reponses/18-documentation-croisee.md",
  "elevator-pitch": "exemples/reponses/19-elevator-pitch.md",
  "energiseur-un-a-neuf": "exemples/reponses/20-energiseur-un-a-neuf.md",
  "enquete-appreciative": "exemples/reponses/21-enquete-appreciative.md",
  "langage-silencieux": "exemples/reponses/22-langage-silencieux.md",
  "les-3c-conserver-cesser-creer": "exemples/reponses/23-les-3c-conserver-cesser-creer.md",
  "les-animaux-de-la-ferme": "exemples/reponses/24-les-animaux-de-la-ferme.md",
  "mandala-holistique": "exemples/reponses/25-mandala-holistique.md",
  "marche-en-aveugle": "exemples/reponses/26-marche-en-aveugle.md",
  "matrice-impact-effort": "exemples/reponses/27-matrice-impact-effort.md",
  "matrice-plus-delta": "exemples/reponses/28-matrice-plus-delta.md",
  "meteo-interieure": "exemples/reponses/29-meteo-interieure.md",
  "methode-des-personas": "exemples/reponses/30-methode-des-personas.md",
  "methode-des-post-it": "exemples/reponses/31-methode-des-post-it.md",
  "six-chapeaux-de-bono": "exemples/reponses/32-six-chapeaux-de-bono.md",
  "methode-walt-disney": "exemples/reponses/33-methode-walt-disney.md",
  "mon-journal": "exemples/reponses/34-mon-journal.md",
  "panorama-des-reussites": "exemples/reponses/35-panorama-des-reussites.md",
  "parole-au-centre": "exemples/reponses/36-parole-au-centre.md",
  "photolangage": "exemples/reponses/37-photolangage.md",
  "pomodoro-synchrone": "exemples/reponses/38-pomodoro-synchrone.md",
  "presentation-croisee": "exemples/reponses/39-presentation-croisee.md",
  "presentations-eclairs": "exemples/reponses/40-presentations-eclairs.md",
  "respiration-collective": "exemples/reponses/41-respiration-collective.md",
  "retrospective-a-4-questions": "exemples/reponses/42-retrospective-a-4-questions.md",
  "reunion-debout": "exemples/reponses/43-reunion-debout.md",
  "reunion-en-marchant": "exemples/reponses/44-reunion-en-marchant.md",
  "souvenir-du-futur": "exemples/reponses/45-souvenir-du-futur.md",
  "sprint-ecriture": "exemples/reponses/46-sprint-ecriture.md",
  "tables-de-decouverte": "exemples/reponses/47-tables-de-decouverte.md",
  "tous-dans-le-meme-bateau": "exemples/reponses/48-tous-dans-le-meme-bateau.md",
  "tri-par-affinites": "exemples/reponses/49-tri-par-affinites.md",
  "vote-a-cinq-doigts": "exemples/reponses/50-vote-a-cinq-doigts.md",
  "vote-a-points": "exemples/reponses/51-vote-a-points.md",
  "world-cafe": "exemples/reponses/52-world-cafe.md"
  }
};
